//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectXml.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SelectXml.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ENVELOPE&gt;
        ///&lt;HEADER&gt;
        ///    &lt;VERSION&gt;1&lt;/VERSION&gt;
        ///    &lt;TALLYREQUEST&gt;Export&lt;/TALLYREQUEST&gt;
        ///    &lt;TYPE&gt;Collection&lt;/TYPE&gt;
        ///    &lt;ID&gt;Custom List of StockItems&lt;/ID&gt;
        ///&lt;/HEADER&gt;
        ///&lt;BODY&gt;
        ///    &lt;DESC&gt;
        ///        &lt;STATICVARIABLES /&gt;
        ///        &lt;TDL&gt;
        ///            &lt;TDLMESSAGE&gt;
        ///                &lt;COLLECTION ISMODIFY=&quot;No&quot; ISFIXED=&quot;No&quot; ISINITIALIZE=&quot;Yes&quot; ISOPTION=&quot;No&quot; ISINTERNAL=&quot;No&quot; NAME=&quot;Custom List of StockItems&quot;&gt;
        ///                    &lt;TYPE&gt;StockItem&lt;/TYPE&gt;
        ///                  
        ///             &lt;FETCH&gt;*&lt;/FETCH&gt;
        ///                &lt;/C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stock {
            get {
                return ResourceManager.GetString("stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ENVELOPE&gt;
        ///	&lt;HEADER&gt;
        ///		&lt;VERSION&gt;1&lt;/VERSION&gt;
        ///		&lt;TALLYREQUEST&gt;Export&lt;/TALLYREQUEST&gt;
        ///		&lt;TYPE&gt;Data&lt;/TYPE&gt;
        ///		&lt;ID&gt;CredFlow_CompanyWiseStockItem&lt;/ID&gt;
        ///	&lt;/HEADER&gt;
        ///	&lt;BODY&gt;
        ///		&lt;DESC&gt;
        ///			&lt;STATICVARIABLES&gt;
        ///				&lt;SVEXPORTFORMAT&gt;$$SysName:XML&lt;/SVEXPORTFORMAT&gt;
        ///			&lt;/STATICVARIABLES&gt;
        ///			&lt;TDL&gt;
        ///				&lt;TDLMESSAGE&gt;
        ///					&lt;REPORT NAME=&quot;CredFlow_CompanyWiseStockItem&quot; ISMODIFY=&quot;No&quot; ISFIXED=&quot;No&quot; ISINITIALIZE=&quot;No&quot; ISOPTION=&quot;No&quot; ISINTERNAL=&quot;No&quot;&gt;
        ///						&lt;FORMS&gt;CredFlow_CompanyWiseStockItem&lt;/FORMS&gt;
        ///					&lt;/REPORT&gt;
        ///					&lt;FORM N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StockItem {
            get {
                return ResourceManager.GetString("StockItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ENVELOPE&gt;
        ///   &lt;HEADER&gt;
        ///     &lt;VERSION&gt;1&lt;/VERSION&gt;
        ///     &lt;TALLYREQUEST&gt;Export&lt;/TALLYREQUEST&gt;
        ///     &lt;TYPE&gt;Collection&lt;/TYPE&gt;
        ///     &lt;ID&gt;Company Collection&lt;/ID&gt;
        ///   &lt;/HEADER&gt;
        ///   &lt;BODY&gt;
        ///     &lt;DESC&gt;
        ///       &lt;STATICVARIABLES&gt;
        ///         &lt;SVEXPORTFORMAT&gt;$$SysName:UTF8JSON&lt;/SVEXPORTFORMAT&gt;
        ///         &lt;SVExportLanguage&gt;$$SysName:UTF8JSON&lt;/SVExportLanguage&gt;
        ///       &lt;/STATICVARIABLES&gt;
        ///       &lt;TDL&gt;
        ///         &lt;TDLMESSAGE&gt;
        ///           &lt;COLLECTION NAME=&quot;Company Collection&quot; ISMODIFY=&quot;No&quot; ISFIXED=&quot;No&quot; ISINITIALIZE=&quot;No&quot; ISOP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StockItemsOnly {
            get {
                return ResourceManager.GetString("StockItemsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ENVELOPE&gt;
        ///	&lt;HEADER&gt;
        ///		&lt;VERSION&gt;1&lt;/VERSION&gt;
        ///		&lt;TALLYREQUEST&gt;Export&lt;/TALLYREQUEST&gt;
        ///		&lt;TYPE&gt;Data&lt;/TYPE&gt;
        ///		&lt;ID&gt;CredFlow_CompanyWiseStockItem&lt;/ID&gt;
        ///	&lt;/HEADER&gt;
        ///	&lt;BODY&gt;
        ///		&lt;DESC&gt;
        ///			&lt;STATICVARIABLES&gt;
        ///				&lt;SVEXPORTFORMAT&gt;$$SysName:XML&lt;/SVEXPORTFORMAT&gt;
        ///			&lt;/STATICVARIABLES&gt;
        ///			&lt;TDL&gt;
        ///				&lt;TDLMESSAGE&gt;
        ///					&lt;REPORT NAME=&quot;CredFlow_CompanyWiseStockItem&quot; ISMODIFY=&quot;No&quot; ISFIXED=&quot;No&quot; ISINITIALIZE=&quot;No&quot; ISOPTION=&quot;No&quot; ISINTERNAL=&quot;No&quot;&gt;
        ///						&lt;FORMS&gt;CredFlow_CompanyWiseStockItem&lt;/FORMS&gt;
        ///					&lt;/REPORT&gt;
        ///					&lt;FORM N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StockTdl {
            get {
                return ResourceManager.GetString("StockTdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ENVELOPE&gt;
        ///	&lt;HEADER&gt;
        ///		&lt;VERSION&gt;1&lt;/VERSION&gt;
        ///		&lt;TALLYREQUEST&gt;Export&lt;/TALLYREQUEST&gt;
        ///		&lt;TYPE&gt;Data&lt;/TYPE&gt;
        ///		&lt;ID&gt;CredFlow_CompanyWiseStockItem&lt;/ID&gt;
        ///	&lt;/HEADER&gt;
        ///	&lt;BODY&gt;
        ///		&lt;DESC&gt;
        ///			&lt;STATICVARIABLES&gt;
        ///				&lt;SVEXPORTFORMAT&gt;$$SysName:XML&lt;/SVEXPORTFORMAT&gt;
        ///			&lt;/STATICVARIABLES&gt;
        ///			&lt;TDL&gt;
        ///				&lt;TDLMESSAGE&gt;
        ///					&lt;REPORT NAME=&quot;CredFlow_CompanyWiseStockItem&quot; ISMODIFY=&quot;No&quot; ISFIXED=&quot;No&quot; ISINITIALIZE=&quot;No&quot; ISOPTION=&quot;No&quot; ISINTERNAL=&quot;No&quot;&gt;
        ///						&lt;FORMS&gt;CredFlow_CompanyWiseStockItem&lt;/FORMS&gt;
        ///					&lt;/REPORT&gt;
        ///					&lt;FORM N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StockTdlSimple {
            get {
                return ResourceManager.GetString("StockTdlSimple", resourceCulture);
            }
        }
    }
}
